# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AttributeEditorSitesCEN
                                 A QGIS plugin
 Permet la mise à jour des sites CEN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
 -------------------
        begin                : 2026-01-07
        copyright            : (C) 2026 by Conservatoire d'Espaces Naturels - Pays de la Loire
        email                : m.goubert@cenpaysdelaloire.fr
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject, QgsVectorLayer
import os.path

# Import du dialogue
from .plugin_sites_cen_dialog import AttributeEditorSitesCENDialog

class AttributeEditorSitesCEN:
    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = self.tr(u'&MAJ des sites CEN')
        self.dlg = None # On initialise à None

    def tr(self, message):
        return QCoreApplication.translate('AttributeEditorSitesCEN', message)

    def initGui(self):
        # On désactive l'icône de ressource pour éviter l'erreur classFactory
        self.add_action(
            None, 
            text=self.tr(u'MAJ des sites CEN'),
            callback=self.run,
            parent=self.iface.mainWindow())

    def add_action(self, icon_path, text, callback, enabled_flag=True, 
                   add_to_menu=True, add_to_toolbar=True, parent=None):
        icon = QIcon(icon_path) if icon_path else QIcon()
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&MAJ des sites CEN'), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        # 1. Sélection du fichier GeoPackage
        filename, _ = QFileDialog.getOpenFileName(
            self.iface.mainWindow(), 
            self.tr("Sélectionner le GeoPackage"), 
            "", "GeoPackage (*.gpkg)")

        if not filename:
            return

        # 2. Chargement de la couche
        # ATTENTION : Remplacez 'sites_cen' par le nom REEL de votre table GPKG
        uri = f"{filename}|layername=sites_cen"
        layer = QgsVectorLayer(uri, "Edition Sites CEN", "ogr")

        if not layer.isValid():
            self.iface.messageBar().pushMessage("Erreur", "Couche introuvable dans le GPKG", level=3)
            return

        # 3. Lancement du dialogue
        if self.dlg is None:
            self.dlg = AttributeEditorSitesCENDialog()

        # Remplissage de la liste à gauche (méthode créée dans le précédent message)
        self.dlg.populate_list(layer)
        
        self.dlg.show()
        result = self.dlg.exec_()
        
        if result:
            # Sauvegarde globale si nécessaire
            pass