# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AttributeEditorSitesCEN
                                 A QGIS plugin
 Permet la mise à jour des sites CEN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-07
        copyright            : (C) 2026 by Conservatoire d'Espaces Naturels - Pays de la Loire
        email                : m.goubert@cenpaysdelaloire.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AttributeEditorSitesCEN class from file AttributeEditorSitesCEN.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plugin_sites_cen import AttributeEditorSitesCEN
    return AttributeEditorSitesCEN(iface)
